set(SOURCE_ROOT ../../src)
set(SOURCES ${SOURCE_ROOT}/${BIN}.cpp)
find_package(Boost REQUIRED system log thread date_time filesystem)
if(Boost_FOUND)
include_directories(${BIN} PUBLIC ${Boost_INCLUDE_DIR})
add_definitions(-DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LIB)
endif()
add_executable(${BIN} ${SOURCES})
target_link_libraries( ${BIN} Boost::log)
if(WIN32)
 set(CMAKE_CXX_FLAGS "/EHsc  -D_WIN32_WINNT=0x600")
 set(myfile ${CMAKE_BINARY_DIR}/RunMe.bat)
 file(WRITE ${myfile} "set PATH=${Boost_LIBRARY_DIRS}\n")
 file(APPEND ${myfile} "Debug\\${BIN}.exe\n")
else()
 set(CMAKE_CXX_FLAGS "-Wall -std=c++0x")
 target_link_libraries( ${BIN} -pthread)
endif()
